name: Travel Or Die
favicon: null
layout_spectrum: 0.5770021446514875
typography_spectrum: 0.39968817750923336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.27125827549025416
  lightness: 0.8465052030514926
  saturation: 0.4079912416636944
  rhythmicContrast: 0.2836042807903141
purpose: []
